name: esm2-idp
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.*t
  - pytorch-cuda=12.4
  - numpy
  - pandas
  - pyyaml
  - tqdm
  - scikit-learn
  - pytest
  - pip
  - pip:
      - fair-esm>=2.0.0